version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000" # Porta mappata tra il container e la macchina locale
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Porta mappata per PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
